fix: `homebrew/cask-fonts` was deprecated
Error: homebrew/cask-fonts was deprecated. This tap is now empty
and all its contents were either deleted or migrated.