fix: jdt server doesn't work
Coc shows the error message:

ERROR: The error Pending response rejected since connection got disposed

The server can not be started correctly, as the latest JDT server has
moved to Java 17 from 1.13.0.

Refer: https://github.com/eclipse/eclipse.jdt.ls/blob/master/CHANGELOG.md#1130-june-30th-2022